# Site settings
title: My Jekyll Project 
subtitle: Jekyll custom theme
email: pvillanueva01@gmail.com
meta_description: Baseline Jekyll theme for site development - bootstrap 
meta_keywords: "jekyll, themes" 
baseurl: "/pv-baseline" # the subpath of your site, e.g. /blog/ 
url: "" # the base hostname & protocol for your site

author: Patricia Villanueva
street_address: 123 Street
city: Miami
state: FL
zip_code: 33161
country: United States of America
phone: 123-456-7894
year: 2018

# Social settings
facebook_url: https://www.facebook.com/pages/University-of-Miami-Libraries/16409329419
instagram_url: https://www.instagram.com/umiamilibraries/
twitter_url: https://twitter.com/UMiamiLibraries

# Google services
google_analytics: #UA-15217512-5

# THEME-SPECIFIC CONFIGURATION
theme_settings:
# Localization strings
  str_next: "Next"
  str_prev: "Previous"
  str_continue_reading: "Read more"    
# Post navigation
  post_navigation: true

# Build settings
markdown: kramdown
highlighter: rouge
future: true
permalink: none

# SASS settings, including Bootstrap SCSS files
sass:
 load_paths:
  - _sass
  - node_modules
  - font-awesome
 style: compressed

# PLUGINS
plugins: 
 - jekyll-paginate
 - jekyll/minibundle
 - jekyll-responsive-image
 - jekyll-autoprefixer

# Do NOT INCLUDE inside _site folder
exclude:
 - node_modules
 - yarn.lock
 - yarn-error.log
 - package.json
 - =3.0.0
 - Gemfile
 - Gemfile.lock
 - font-awesome/scss
 - LICENCE
 - README.md

# Minibundle
minibundle:
 minifier_commands:
  js: node_modules/.bin/uglifyjs

# Responsive Images
responsive_image:
 template: _includes/responsive-image.html
 default_quality: 75
 sizes:
  - width: 320 #for xs-mobile
  - width: 640 # for mobile
  - width: 800 # for iPad 
  - width: 1024 # for min desktop
  - width: 1280 # for 1280
 base_path: images
 output_path_format: images/resized/%{filename}-%{width}x%{height}.%{extension}
 save_to_source: true
 cache: false

# Pagination
paginate: 5
paginate_path: "page:num"