# Site settings
title: My Jekyll Project 
subtitle: Jekyll custom theme
email: pvillanueva01@gmail.com
meta_description: Baseline Jekyll theme for site development - bootstrap-material design- 
meta_keywords: "jekyll, themes" 
baseurl: "/pv-baseline" # the subpath of your site, e.g. /blog/ 
url: "" # the base hostname & protocol for your site

author: Patricia Villanueva
street_address: 123 Street
city: Miami
state: FL
zip_code: 33161
country: United States of America
phone: 123-456-7894
year: 2018

# Social settings
facebook_url: https://www.facebook.com/pages/University-of-Miami-Libraries/16409329419
instagram_url: https://www.instagram.com/umiamilibraries/
twitter_url: https://twitter.com/UMiamiLibraries

# Google services
google_analytics: #UA-15217512-5

# THEME-SPECIFIC CONFIGURATION
theme_settings:
# Localization strings
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more"    
# Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
highlighter: rouge
future: true
permalink: none

# SASS settings, including Bootstrap SCSS files
sass:
 load_paths:
  - _sass
  - node_modules
 style: compressed

# PLUGINS
plugins: 
 - jekyll-paginate
 - jekyll-minifier
 - jekyll-assets

# Do NOT INCLUDE inside _site folder
exclude:
 - node_modules
 - yarn.lock
 - package.json
 - =3.0.0

# Settings for Jekyll Assets Plugin
assets:
 compress:
  css: false
  js: true
 cache: default
 prefix: "/assets"
 digest: true 
 sources:
  - _assets/scripts
  - node_modules/bootstrap/dist/js
  - node_modules/jquery/dist
  - node_modules/popper.js/dist

# Minifify JS files
jekyll-minifier:
 compress_javascript: true

